//! Virt-viewer (.vv) file importer.
//!
//! Parses `.vv` files generated by libvirt/Proxmox VE for SPICE and VNC
//! connections. These INI-style files contain a `[virt-viewer]` section
//! with connection parameters like host, port, TLS settings, and proxy.
//!
//! Inline PEM CA certificates (common in Proxmox VE tickets) are
//! automatically saved to `$XDG_DATA_HOME/rustconn/certs/` so the
//! connection can use TLS immediately without manual file management.
//!
//! Reference: <https://manpages.debian.org/testing/virt-viewer/remote-viewer.1.en.html>

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use secrecy::SecretString;

use crate::error::ImportError;
use crate::models::{
    Connection, Credentials, PasswordSource, ProtocolConfig, SpiceConfig, VncConfig,
};

use super::traits::{ImportResult, ImportSource, SkippedEntry, read_import_file};

/// Importer for virt-viewer `.vv` connection files.
///
/// Supports SPICE and VNC connection types as defined by the
/// virt-viewer file format used by libvirt, Proxmox VE, and oVirt.
pub struct VirtViewerImporter;

impl Default for VirtViewerImporter {
    fn default() -> Self {
        Self::new()
    }
}

impl VirtViewerImporter {
    /// Creates a new virt-viewer importer
    #[must_use]
    pub const fn new() -> Self {
        Self
    }

    /// Parses INI-style content into key-value pairs for the
    /// `[virt-viewer]` section.
    fn parse_vv_section(content: &str) -> Option<HashMap<String, String>> {
        let mut in_section = false;
        let mut fields = HashMap::new();

        for line in content.lines() {
            let line = line.trim();

            if line.is_empty() || line.starts_with('#') || line.starts_with(';') {
                continue;
            }

            if line.eq_ignore_ascii_case("[virt-viewer]") {
                in_section = true;
                continue;
            }

            // Another section starts — stop
            if line.starts_with('[') && line.ends_with(']') {
                if in_section {
                    break;
                }
                continue;
            }

            if in_section && let Some(eq_pos) = line.find('=') {
                let key = line[..eq_pos].trim().to_lowercase();
                let value = line[eq_pos + 1..].trim().to_string();
                fields.insert(key, value);
            }
        }

        if fields.is_empty() {
            None
        } else {
            Some(fields)
        }
    }

    /// Converts parsed virt-viewer fields into a `Connection`.
    fn convert_to_connection(
        fields: &HashMap<String, String>,
        source_path: &str,
        result: &mut ImportResult,
    ) -> Option<Connection> {
        // Determine protocol type
        let proto = fields
            .get("type")
            .map(|s| s.to_lowercase())
            .unwrap_or_default();

        let (protocol_config, default_port) = match proto.as_str() {
            "spice" => {
                let tls_port = fields.get("tls-port").and_then(|p| p.parse::<u16>().ok());
                let has_tls = tls_port.is_some();

                let ca_cert_path = fields.get("ca").and_then(|ca| {
                    if ca.starts_with("-----BEGIN") {
                        // Inline PEM — save to a file automatically so TLS works
                        // immediately (critical for Proxmox VE short-lived tickets).
                        match save_inline_pem_cert(ca, source_path) {
                            Ok(saved_path) => {
                                result.record_warning(format!(
                                    "Inline CA certificate saved to {}",
                                    saved_path.display()
                                ));
                                Some(saved_path)
                            }
                            Err(reason) => {
                                result.add_skipped(SkippedEntry::with_location(
                                    source_path,
                                    format!(
                                        "Could not save inline PEM CA certificate: {reason}. \
                                         Save it manually and set the CA path in connection settings."
                                    ),
                                    source_path,
                                ));
                                None
                            }
                        }
                    } else {
                        Some(PathBuf::from(ca))
                    }
                });

                // Store proxy URL in SpiceConfig so it's used for connections
                let proxy = fields.get("proxy").filter(|p| !p.is_empty()).cloned();

                (
                    ProtocolConfig::Spice(SpiceConfig {
                        tls_enabled: has_tls,
                        ca_cert_path,
                        proxy,
                        ..SpiceConfig::default()
                    }),
                    default_port_for_spice(fields),
                )
            }
            "vnc" => (ProtocolConfig::Vnc(VncConfig::default()), 5900u16),
            "" => {
                result.add_skipped(SkippedEntry::with_location(
                    source_path,
                    "Missing 'type' field in [virt-viewer] section",
                    source_path,
                ));
                return None;
            }
            other => {
                result.add_skipped(SkippedEntry::with_location(
                    source_path,
                    format!("Unsupported virt-viewer type: {other}"),
                    source_path,
                ));
                return None;
            }
        };

        // Extract host
        let host = match fields.get("host") {
            Some(h) if !h.is_empty() => h.clone(),
            _ => {
                result.add_skipped(SkippedEntry::with_location(
                    source_path,
                    "No host specified in [virt-viewer] section",
                    source_path,
                ));
                return None;
            }
        };

        // Extract port: prefer tls-port for SPICE, then port
        let port = fields
            .get("tls-port")
            .and_then(|p| p.parse::<u16>().ok())
            .or_else(|| fields.get("port").and_then(|p| p.parse::<u16>().ok()))
            .unwrap_or(default_port);

        // Build connection name from title or host
        let name = fields
            .get("title")
            .filter(|t| !t.is_empty())
            .cloned()
            .unwrap_or_else(|| format!("{host}:{port}"));

        let mut conn = Connection::new(name, host, port, protocol_config);

        // Handle password — store as credential, mark source as Vault
        if let Some(pw) = fields.get("password").filter(|p| !p.is_empty()) {
            conn.password_source = PasswordSource::Vault;
            let creds = Credentials {
                username: None,
                password: Some(SecretString::from(pw.clone())),
                key_passphrase: None,
                domain: None,
            };
            result.credentials.insert(conn.id, creds);
        }

        // Store host-subject as a tag for reference
        if let Some(subj) = fields.get("host-subject").filter(|s| !s.is_empty()) {
            conn.tags.push(format!("host-subject:{subj}"));
        }

        conn.tags.push("imported:virt-viewer".to_string());

        Some(conn)
    }
}

/// Saves an inline PEM certificate string to a file on disk.
///
/// The certificate is stored in `$XDG_DATA_HOME/rustconn/certs/` with a
/// filename derived from the source path (FNV-1a hash) to avoid collisions.
/// The file is created with mode 0600 to prevent other users from reading it.
///
/// # Errors
///
/// Returns a human-readable error string if the directory cannot be created,
/// the PEM content is invalid, or the file cannot be written.
fn save_inline_pem_cert(pem_content: &str, source_hint: &str) -> Result<PathBuf, String> {
    // Basic PEM validation: must contain both BEGIN and END markers
    if !pem_content.contains("-----BEGIN") {
        return Err("PEM content missing -----BEGIN marker".to_string());
    }
    // Decode escaped newlines first to check for END marker
    let decoded = pem_content.replace("\\n", "\n");
    if !decoded.contains("-----END") {
        return Err(
            "PEM content missing -----END marker — certificate may be truncated".to_string(),
        );
    }

    let certs_dir = dirs::data_dir()
        .ok_or_else(|| "cannot determine XDG data directory".to_string())?
        .join("rustconn")
        .join("certs");

    std::fs::create_dir_all(&certs_dir)
        .map_err(|e| format!("failed to create {}: {e}", certs_dir.display()))?;

    // Restrict directory permissions to owner only (rwx------)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let dir_perms = std::fs::Permissions::from_mode(0o700);
        let _ = std::fs::set_permissions(&certs_dir, dir_perms);
    }

    // Generate a short stable filename from the source path
    let hash = simple_hash(source_hint);
    let filename = format!("ca-{hash}.pem");
    let cert_path = certs_dir.join(&filename);

    std::fs::write(&cert_path, decoded.as_bytes())
        .map_err(|e| format!("failed to write {}: {e}", cert_path.display()))?;

    // Restrict file permissions to owner read/write only (rw-------)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let file_perms = std::fs::Permissions::from_mode(0o600);
        std::fs::set_permissions(&cert_path, file_perms)
            .map_err(|e| format!("failed to set permissions on {}: {e}", cert_path.display()))?;
    }

    Ok(cert_path)
}

/// Produces a short hex hash (first 16 chars of a simple FNV-like digest).
///
/// We avoid pulling in a full SHA crate for a single non-security use.
fn simple_hash(input: &str) -> String {
    // FNV-1a 64-bit
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in input.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0100_0000_01b3);
    }
    format!("{hash:016x}")
}

/// Returns the appropriate default port for a SPICE connection
/// based on whether TLS is configured.
fn default_port_for_spice(fields: &HashMap<String, String>) -> u16 {
    fields
        .get("tls-port")
        .and_then(|p| p.parse::<u16>().ok())
        .or_else(|| fields.get("port").and_then(|p| p.parse::<u16>().ok()))
        .unwrap_or(5900)
}

impl VirtViewerImporter {
    /// Parses a single `.vv` file and returns the first connection.
    ///
    /// Convenience method for startup actions (analogous to
    /// `RdpFileImporter::parse_rdp_file`). For batch import with
    /// skipped-entry reporting, use `import_from_path()` instead.
    ///
    /// # Errors
    ///
    /// Returns `ImportError` if the file cannot be read, has no
    /// `[virt-viewer]` section, or the connection type is unsupported.
    pub fn parse_vv_file(path: &Path) -> Result<Connection, ImportError> {
        let content = read_import_file(path, "virt-viewer")?;
        let source_path = path.display().to_string();

        let fields = Self::parse_vv_section(&content).ok_or_else(|| ImportError::ParseError {
            source_name: "virt-viewer".to_string(),
            reason: "No [virt-viewer] section found in file".to_string(),
        })?;

        let mut result = ImportResult::new();
        Self::convert_to_connection(&fields, &source_path, &mut result).ok_or_else(|| {
            // Use the first skipped entry reason if available
            let reason = result
                .skipped
                .first()
                .map(|s| s.reason.clone())
                .unwrap_or_else(|| "Failed to parse virt-viewer connection".to_string());
            ImportError::ParseError {
                source_name: "virt-viewer".to_string(),
                reason,
            }
        })
    }
}

impl ImportSource for VirtViewerImporter {
    fn source_id(&self) -> &'static str {
        "virt_viewer"
    }

    fn display_name(&self) -> &'static str {
        "Virt-Viewer (.vv)"
    }

    fn is_available(&self) -> bool {
        // File-based import — always available
        true
    }

    fn default_paths(&self) -> Vec<PathBuf> {
        // No default paths — user selects the file
        Vec::new()
    }

    fn import(&self) -> Result<ImportResult, ImportError> {
        Err(ImportError::FileNotFound(PathBuf::from(
            "No default paths for virt-viewer files. Use import_from_path().",
        )))
    }

    fn import_from_path(&self, path: &Path) -> Result<ImportResult, ImportError> {
        let content = read_import_file(path, "virt-viewer")?;
        let source_path = path.display().to_string();

        let mut result = ImportResult::new();

        let Some(fields) = Self::parse_vv_section(&content) else {
            return Err(ImportError::ParseError {
                source_name: "virt-viewer".to_string(),
                reason: "No [virt-viewer] section found in file".to_string(),
            });
        };

        if let Some(conn) = Self::convert_to_connection(&fields, &source_path, &mut result) {
            result.add_connection(conn);
        }

        Ok(result)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    fn write_vv_file(content: &str) -> NamedTempFile {
        let mut f = NamedTempFile::new().expect("tempfile");
        f.write_all(content.as_bytes()).expect("write");
        f.flush().expect("flush");
        f
    }

    #[test]
    fn test_parse_spice_proxmox() {
        let content = "\
[virt-viewer]
type=spice
host=pvespiceproxy:6991bb86:207:nuc::19b918cb428c22c74b6099263598d66d
tls-port=61000
password=secret123
title=VM 200 - test
proxy=http://192.168.1.100:3128
host-subject=OU=PVE Cluster Node,O=Proxmox Virtual Environment,CN=nuc.example.org
delete-this-file=1
toggle-fullscreen=Shift+F11
release-cursor=Ctrl+Alt+R
secure-attention=Ctrl+Alt+Ins
ca=-----BEGIN CERTIFICATE-----\\nMIIFake...\\n-----END CERTIFICATE-----
";
        let f = write_vv_file(content);
        let importer = VirtViewerImporter::new();
        let result = importer.import_from_path(f.path()).expect("import");

        assert_eq!(result.connections.len(), 1);
        let conn = &result.connections[0];
        assert_eq!(conn.name, "VM 200 - test");
        assert_eq!(conn.port, 61000);
        assert!(matches!(
            conn.protocol_config,
            ProtocolConfig::Spice(ref s) if s.tls_enabled
        ));
        assert_eq!(conn.password_source, PasswordSource::Vault);
        assert!(result.credentials.contains_key(&conn.id));
        // Proxy should be stored in SpiceConfig, not as a tag
        assert!(matches!(
            conn.protocol_config,
            ProtocolConfig::Spice(ref s) if s.proxy.as_deref() == Some("http://192.168.1.100:3128")
        ));
        assert!(conn.tags.iter().any(|t| t.starts_with("host-subject:")));
        // Inline PEM CA should be saved to a file automatically
        assert!(
            matches!(
                conn.protocol_config,
                ProtocolConfig::Spice(ref s) if s.ca_cert_path.is_some()
            ),
            "Expected ca_cert_path to be set after inline PEM save"
        );
        // A warning should inform the user where the cert was saved
        assert!(
            result.warnings.iter().any(|w| w.contains("Inline CA certificate saved")),
            "Expected a warning about saved CA certificate"
        );
        // Verify the saved file exists and contains decoded PEM
        if let ProtocolConfig::Spice(ref s) = conn.protocol_config {
            let ca_path = s.ca_cert_path.as_ref().unwrap();
            assert!(ca_path.exists(), "Saved CA cert file should exist");
            let contents = std::fs::read_to_string(ca_path).unwrap();
            assert!(
                contents.contains("-----BEGIN CERTIFICATE-----"),
                "Saved file should contain PEM header"
            );
            // Cleanup
            let _ = std::fs::remove_file(ca_path);
        }
    }

    #[test]
    fn test_parse_vnc() {
        let content = "\
[virt-viewer]
type=vnc
host=192.168.1.50
port=5901
title=My VNC VM
";
        let f = write_vv_file(content);
        let importer = VirtViewerImporter::new();
        let result = importer.import_from_path(f.path()).expect("import");

        assert_eq!(result.connections.len(), 1);
        let conn = &result.connections[0];
        assert_eq!(conn.name, "My VNC VM");
        assert_eq!(conn.port, 5901);
        assert!(matches!(conn.protocol_config, ProtocolConfig::Vnc(_)));
    }

    #[test]
    fn test_missing_section() {
        let content = "just some random text\nno section here\n";
        let f = write_vv_file(content);
        let importer = VirtViewerImporter::new();
        let err = importer.import_from_path(f.path()).unwrap_err();
        assert!(matches!(err, ImportError::ParseError { .. }));
    }

    #[test]
    fn test_missing_host() {
        let content = "\
[virt-viewer]
type=spice
tls-port=61000
";
        let f = write_vv_file(content);
        let importer = VirtViewerImporter::new();
        let result = importer.import_from_path(f.path()).expect("import");
        assert!(result.connections.is_empty());
        assert_eq!(result.skipped.len(), 1);
    }

    #[test]
    fn test_unsupported_type() {
        let content = "\
[virt-viewer]
type=rdp
host=example.com
port=3389
";
        let f = write_vv_file(content);
        let importer = VirtViewerImporter::new();
        let result = importer.import_from_path(f.path()).expect("import");
        assert!(result.connections.is_empty());
        assert_eq!(result.skipped.len(), 1);
    }

    #[test]
    fn test_name_fallback_to_host_port() {
        let content = "\
[virt-viewer]
type=spice
host=10.0.0.1
port=5900
";
        let f = write_vv_file(content);
        let importer = VirtViewerImporter::new();
        let result = importer.import_from_path(f.path()).expect("import");
        assert_eq!(result.connections[0].name, "10.0.0.1:5900");
    }

    #[test]
    fn test_inline_pem_missing_end_marker() {
        // PEM without -----END should be rejected with a meaningful error
        let content = "\
[virt-viewer]
type=spice
host=test.example.com
tls-port=61000
ca=-----BEGIN CERTIFICATE-----\\nMIIFakeContentWithoutEndMarker
";
        let f = write_vv_file(content);
        let importer = VirtViewerImporter::new();
        let result = importer.import_from_path(f.path()).expect("import");
        // Connection should still be created but without ca_cert_path
        assert_eq!(result.connections.len(), 1);
        assert!(
            matches!(
                result.connections[0].protocol_config,
                ProtocolConfig::Spice(ref s) if s.ca_cert_path.is_none()
            ),
            "Expected no ca_cert_path when PEM is invalid (missing END marker)"
        );
        // Should have a skipped entry explaining the issue
        assert!(
            result.skipped.iter().any(|s| s.reason.contains("END marker")),
            "Expected skipped entry mentioning missing END marker"
        );
    }

    #[test]
    fn test_inline_pem_multiline_full_cert() {
        // Simulate a realistic multi-line Proxmox PEM certificate
        let pem_lines = [
            "-----BEGIN CERTIFICATE-----",
            "MIIFnTCCA4WgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwYTELMAkGA1UEBhMCVVMx",
            "EDAOBgNVBAgMB0FyaXpvbmExEDAOBgNVBAcMB1Bob2VuaXgxDTALBgNVBAoMBFRl",
            "c3QxHzAdBgNVBAMMFlByb3htb3ggVkUgVGVzdCBDQSAyMDI0MB4XDTI0MDEwMTAw",
            "MDAwMFoXDTM0MDEwMTAwMDAwMFowYTELMAkGA1UEBhMCVVMxEDAOBgNVBAgMB0Fy",
            "aXpvbmExEDAOBgNVBAcMB1Bob2VuaXgxDTALBgNVBAoMBFRlc3QxHzAdBgNVBAMM",
            "FlByb3htb3ggVkUgVGVzdCBDQSAyMDI0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8A",
            "-----END CERTIFICATE-----",
        ];
        // Proxmox INI format uses literal \\n between lines
        let ca_value = pem_lines.join("\\n");

        let content = format!(
            "[virt-viewer]\ntype=spice\nhost=pve.example.org\ntls-port=61234\nca={ca_value}\n"
        );
        let f = write_vv_file(&content);
        let importer = VirtViewerImporter::new();
        let result = importer.import_from_path(f.path()).expect("import");

        assert_eq!(result.connections.len(), 1);
        let conn = &result.connections[0];
        if let ProtocolConfig::Spice(ref s) = conn.protocol_config {
            let ca_path = s.ca_cert_path.as_ref().expect("ca_cert_path should be set");
            assert!(ca_path.exists(), "Saved CA cert file should exist");
            let contents = std::fs::read_to_string(ca_path).unwrap();
            assert!(contents.contains("-----BEGIN CERTIFICATE-----"));
            assert!(contents.contains("-----END CERTIFICATE-----"));
            // Verify newlines were decoded properly (no literal \\n remains)
            assert!(
                !contents.contains("\\n"),
                "Literal backslash-n should be decoded to real newlines"
            );
            // Verify file permissions on Unix
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let perms = std::fs::metadata(ca_path).unwrap().permissions();
                assert_eq!(
                    perms.mode() & 0o777,
                    0o600,
                    "PEM file should have 0600 permissions"
                );
            }
            // Cleanup
            let _ = std::fs::remove_file(ca_path);
        } else {
            panic!("Expected Spice protocol config");
        }
    }
}
