//! Connection group model for hierarchical organization.

use std::path::PathBuf;

use chrono::{DateTime, Utc};

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::PasswordSource;
use super::SshAuthMethod;
use crate::sync::SyncMode;

/// A hierarchical group for organizing connections
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConnectionGroup {
    /// Unique identifier for the group
    pub id: Uuid,
    /// Human-readable name for the group
    pub name: String,
    /// Parent group ID (None for root-level groups)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Uuid>,
    /// Whether the group is expanded in the UI
    #[serde(default)]
    pub expanded: bool,
    /// Timestamp when the group was created
    pub created_at: DateTime<Utc>,
    /// Timestamp when the group's synced content was last modified.
    ///
    /// Drives Simple Sync conflict resolution (newer wins). Groups loaded from
    /// configurations written before this field existed deserialize to the Unix
    /// epoch (see [`group_updated_at_default`]), so any genuine later edit wins
    /// the merge while two un-edited copies tie and never overwrite each other.
    #[serde(default = "group_updated_at_default")]
    pub updated_at: DateTime<Utc>,
    /// Sort order for manual ordering (lower values appear first)
    #[serde(default)]
    pub sort_order: i32,
    /// Username for inheritance
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Domain for inheritance
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Password source and config for inheritance
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password_source: Option<PasswordSource>,
    /// Optional description/notes for the group
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Custom icon for the group (emoji/unicode character or GTK icon name)
    ///
    /// When `None`, the default folder icon is used.
    /// Examples: `"🇺🇦"`, `"🏢"`, `"starred-symbolic"`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    /// SSH authentication method for inheritance by child connections
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ssh_auth_method: Option<SshAuthMethod>,
    /// SSH key path for inheritance (LOCAL-ONLY, not synced)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ssh_key_path: Option<PathBuf>,
    /// SSH ProxyJump for inheritance
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ssh_proxy_jump: Option<String>,
    /// ID of an SSH connection to use as jump host for all connections in this group.
    /// Takes precedence over `ssh_proxy_jump` text field. (LOCAL-ONLY, not synced)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ssh_jump_host_id: Option<Uuid>,
    /// SSH agent socket override for inheritance (LOCAL-ONLY)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ssh_agent_socket: Option<String>,
    /// Cloud Sync mode for this group (None, Master, or Import).
    #[serde(default)]
    pub sync_mode: SyncMode,
    /// Dynamic folder configuration (script-generated connections).
    /// When set, this group's connections are generated by executing the script.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dynamic_folder: Option<super::DynamicFolderConfig>,
    /// Filename in the sync directory (e.g., `"production-servers.rcn"`).
    /// Fixed at first export and never changes even if the group is renamed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sync_file: Option<String>,
    /// Timestamp of the last successful sync operation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_synced_at: Option<DateTime<Utc>>,
    /// Expect rules for inheritance by child connections.
    /// Connections with empty `automation.expect_rules` inherit from their group chain.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub expect_rules: Vec<crate::automation::ExpectRule>,
    /// Post-login scripts for inheritance by child connections.
    /// Connections with empty `automation.post_login_scripts` inherit from their group chain.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub post_login_scripts: Vec<String>,
}

/// Default `updated_at` for groups written before edit-tracking existed.
///
/// Returns the Unix epoch so a genuine later edit (which bumps `updated_at` to
/// "now") always wins the Simple Sync merge, while two un-edited legacy copies
/// on different devices tie and never spuriously overwrite each other.
fn group_updated_at_default() -> DateTime<Utc> {
    // 0 is always a valid timestamp; the fallback is unreachable in practice.
    DateTime::from_timestamp(0, 0).unwrap_or_else(Utc::now)
}

impl ConnectionGroup {
    /// Creates a new root-level group
    #[must_use]
    pub fn new(name: String) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            name,
            parent_id: None,
            expanded: true,
            created_at: now,
            updated_at: now,
            sort_order: 0,
            username: None,
            domain: None,
            password_source: None,
            description: None,
            icon: None,
            ssh_auth_method: None,
            ssh_key_path: None,
            ssh_proxy_jump: None,
            ssh_jump_host_id: None,
            ssh_agent_socket: None,
            sync_mode: SyncMode::None,
            dynamic_folder: None,
            sync_file: None,
            last_synced_at: None,
            expect_rules: Vec::new(),
            post_login_scripts: Vec::new(),
        }
    }

    /// Creates a new group with a parent
    #[must_use]
    pub fn with_parent(name: String, parent_id: Uuid) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            name,
            parent_id: Some(parent_id),
            expanded: true,
            created_at: now,
            updated_at: now,
            sort_order: 0,
            username: None,
            domain: None,
            password_source: None,
            description: None,
            icon: None,
            ssh_auth_method: None,
            ssh_key_path: None,
            ssh_proxy_jump: None,
            ssh_jump_host_id: None,
            ssh_agent_socket: None,
            sync_mode: SyncMode::None,
            dynamic_folder: None,
            sync_file: None,
            last_synced_at: None,
            expect_rules: Vec::new(),
            post_login_scripts: Vec::new(),
        }
    }

    /// Returns true if this is a root-level group
    #[must_use]
    pub const fn is_root(&self) -> bool {
        self.parent_id.is_none()
    }

    /// Updates the `updated_at` timestamp to now.
    ///
    /// Call this on genuine user edits to a group's synced content so Simple
    /// Sync propagates the change. Do not call it for sync bookkeeping (e.g.
    /// `last_synced_at`) — that would churn the merge clock.
    pub fn touch(&mut self) {
        self.updated_at = Utc::now();
    }
}

/// Collects all descendant group IDs from a slice, starting from `root_id`.
///
/// Uses BFS with a parent→children index for O(n) traversal.
/// The returned vector includes `root_id` as the first element.
#[must_use]
pub fn collect_descendant_group_ids(root_id: Uuid, groups: &[ConnectionGroup]) -> Vec<Uuid> {
    use std::collections::HashMap;

    let mut children_index: HashMap<Uuid, Vec<Uuid>> = HashMap::new();
    for group in groups {
        if let Some(parent) = group.parent_id {
            children_index.entry(parent).or_default().push(group.id);
        }
    }

    let mut result = vec![root_id];
    let mut i = 0;
    while i < result.len() {
        let current = result[i];
        if let Some(children) = children_index.get(&current) {
            for &child_id in children {
                if !result.contains(&child_id) {
                    result.push(child_id);
                }
            }
        }
        i += 1;
    }

    result
}
